# Generated by Django 5.0.7 on 2024-08-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_panier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
